name: Terragrunt Deployment

on:
  push:
    paths:
      - 'infra-resources/**'

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Determine Path
        id: path
        run: echo "::set-output name=path::$(echo ${{ github.event.head_commit.message }} | grep -oP '(?<=path:)[^ ]*')"

      - name: Terragrunt Init
        run: |
          cd ${{ steps.path.outputs.path }}
          terragrunt run-all init

      - name: Terragrunt Apply
        run: |
          cd ${{ steps.path.outputs.path }}
          terragrunt run-all apply --terragrunt-non-interactive