name: AWS Credentials Test

on:
  #workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configurar las credenciales de AWS
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Referencia al secreto
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Referencia al secreto 
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Set up SSH for GitHub
      run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.GIT_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
          # Esto configura la clave SSH para acceder a GitHub y agrega github.com al archivo known_hosts
        
    # Paso 4: Listar los buckets S3 (opcional) para asegurar que puedes interactuar con AWS
    - name: List S3 Buckets
      run: |
        echo "Listando los buckets de S3..."
        aws s3 ls
    - name: Try ssh
      run: |
        git clone git@github.com:campusdualdevopsGrupo2/cloud-resources.git

