name: Update node app

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
          with:
            aws-region: ${{secrets.AWS_DEFAULT_REGION}}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Referencia al secreto
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Referencia al secreto
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Si es necesario (solo para credenciales temporales)

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
        
        - name: Debug
          run: |             
            ls
            pwd
            ls $TERRAFORM_CLI_PATH 
        - name: Update eks task
          run: |
            sleep 10
            terraform init
            terraform taint aws_ecs_task_definition.node_task
            terraform apply -auto-approve
          working-directory: ./modules/app_node